services:
  redis:
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashy
    volumes:
      - pg_data:/var/lib/postgresql
  flask:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/flashy
      REDIS_URL: redis://redis:6379
  react:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - flask

volumes:
  pg_data: